name: Bug Report
description: Create a report to help us improve
title: '[Bug] '
labels:
- bug
assignees: []
body:
- type: textarea
  id: describe-bug
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
    placeholder: What's the issue you're experiencing?
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior
    placeholder: '1. Go to ''...''

      2. Click on ''....''

      3. Scroll down to ''....''

      4. See error

      '
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
    placeholder: What did you expect to happen instead?
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    placeholder: You can drag and drop images into this issue.
- type: markdown
  attributes:
    value: '**Smartphone (please complete the following information):**'
- type: input
  id: smartphone-device
  attributes:
    label: Device
    placeholder: e.g. Samsung Galaxy S23
  validations:
    required: true
- type: input
  id: smartphone-os
  attributes:
    label: OS
    placeholder: e.g. Android 14
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of Driftly are you running?
    options:
    - v1.5.0 (Latest)
    - v1.4.0
    - v1.3.0
    - v1.2.0
    - v1.1.0
    - v1.0.0
    default: 0
  validations:
    required: true
- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    description: 'Carefully read and work through this check list

      '
    options:
    - label: I understand that the issue will be (ignored/closed) if I intentionally
        remove or skip any mandatory field.
      required: true
