name: Crash Report
description: Submit crash logs to help us fix issues
title: '[Crash] '
labels:
- crash
assignees: []
body:
- type: textarea
  id: crash-log
  attributes:
    label: Paste crash log
    description: Paste your crash log **inside triple backticks (```)** so it shows
      up properly formatted.
    placeholder: "```\njava.lang.RuntimeException: Example crash\n    at com.example.MyClass.myMethod(MyClass.java:123)\n\
      \    \n```\n"
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: You can write additional context here, e.g. what action exactly caused
      the crash
    placeholder: 'What caused the crash?

      In which screen did the app crash?

      '
  validations:
    required: false
- type: markdown
  attributes:
    value: '**These fields are needed in case you used other crash reporting apps
      for logs:**'
- type: input
  id: smartphone-device
  attributes:
    label: Device
    placeholder: e.g. Samsung Galaxy S23
  validations:
    required: true
- type: input
  id: smartphone-os
  attributes:
    label: OS
    placeholder: e.g. Android 14
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of Driftly are you running?
    options:
    - v1.8.1 (Latest)
    - v1.8.0
    - v1.7.0
    - v1.6.0
    - v1.5.1
    - v1.5.0
    - v1.4.0
    - v1.3.0
    - v1.2.0
    - v1.1.0
    - v1.0.0
    default: 0
  validations:
    required: true
- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    description: Carefully read and work through this checklist
    options:
    - label: I understand that the issue will be (ignored/closed) if I intentionally
        remove or skip any mandatory field.
      required: true
